### ISSUE TITLE
Add-on don't start

### ISSUE THREAD

**Issue by neonline78** [schumijo/homeassistant-addons#9]
Hi Schumijo,
from today the add-on start but return some errors and stop itself.
This is my log:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:20:55] INFO: Generating config.yaml from options.json
[18:21:00] INFO: Configuration :
[18:21:00] INFO: # Generated by homeassistant, do not edit!
# Edit configuration only at the Add-on configuration tab!
debug: false
delay_device: 60
delay_site: 10
homeassistant_config:
  code: 110910
  code_arm_required: false
  code_disarm_required: true
mqtt:
  client-id: somfy-protect
  ha_discover_prefix: homeassistant
  host: 192.168.1.99
  password: mqttpassword
  port: 1883
  topic_prefix: somfyProtect2mqtt
  username: mqtt_user
somfy_protect:
  password: Lorenzo2010somfy
  sites:
    - Casa Guerra
  username: massi.gi@gmail.com
[18:21:01] INFO: Image build
[18:21:01] INFO: starting original stuff...
2021-12-09 18:21:03,576 [INFO] Starting SomfyProtect2Mqtt
2021-12-09 18:21:03,578 [INFO] Reading config file config/config.yaml
2021-12-09 18:21:03,594 [INFO] Init SomfyProtect2Mqtt
Traceback (most recent call last):
  File "/usr/src/SomfyProtect2MQTT/somfyProtect2Mqtt/main.py", line 29, in <module>
    SOMFY_PROTECT = SomfyProtect2Mqtt(CONFIG)
  File "/usr/src/SomfyProtect2MQTT/somfyProtect2Mqtt/somfy_protect_2_mqtt.py", line 56, in __init__
    self.somfy_protect_api = init_somfy_protect(username=username, password=password)
  File "/usr/src/SomfyProtect2MQTT/somfyProtect2Mqtt/somfy_protect.py", line 39, in init_somfy_protect
    set_token(api.request_token())
  File "/usr/lib/python3.8/site-packages/somfy_protect_api/api/somfy_protect_api.py", line 304, in request_token
    return self._oauth.fetch_token(
  File "/usr/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 360, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 429, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 425, in parse_token_response
    validate_token_parameters(params)
  File "/usr/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 435, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

Any idea?
Thank you
Massimiliano

**Comment by foXaCe** [comment]
hello same problem for me

**Comment by Minims** [comment]
I don't know why. I think the behavior has change on Somfy side.

https://github.com/Minims/somfy-protect-api/blob/master/somfy_protect_api/api/somfy_protect_api.py#L304 
This is Failing with an HTTP 500 error from Somfy.

**Comment by neonline78** [comment]
Hi Minims,
One change by Somfy it's also what I think...

**Comment by Minims** [comment]
Fix in https://github.com/schumijo/homeassistant-addons/pull/10

**Comment by yukes33** [comment]
Hi everyone, 
Same for me. Thanks Minims for trying (maybe succeeding, I can't test it yet) to help us.

**Comment by Minims** [comment]
I use the dev version it works for me. if you use the dev add-on you might need to click on 'rebuild'

**Comment by neonline78** [comment]
Working! Thank youuuuu

**Comment by yukes33** [comment]
Same for me. The dev add-on is fixing it. Thank you very much
